# .github/workflows/ci.yml

name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # 1) Check out your code
      - uses: actions/checkout@v3

      # 2) Set up Python
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      # 3) Install dependencies (including pytest)
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip               # upgrade pip
          pip install -r requirements.txt                   # your project deps
          pip install pytest                                 # explicitly install pytest :contentReference[oaicite:0]{index=0}

      # 4) Run tests
      - name: Run pytest
        run: pytest # now ‘pytest’ will be on PATH :contentReference[oaicite:1]{index=1}
