name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # 1) Check out your code
      - uses: actions/checkout@v3

      # 2) Set up Python
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      # 3) Install dependencies (including pytest + your package)
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .                     
          pip install -r requirements.txt
          pip install pytest

      # 4) Run tests
      - name: Run pytest
        run: pytest
